// productData.js v1.0-full 全量功能版
// 保險產品數據源 | 完整融資參數 | 兼容全量業務邏輯
const productData = {
    version: "v1.0-full",
    generated_at: "2026-06-24",
    scope: "INS01+INS02 共10款產品 | 全量融資演算支持",
    // 匯率配置
    base_currency: "HKD",
    exchange_rates: {
        "HKD_to_USD": 0.128,
        "USD_to_HKD": 7.8,
        "CNY_to_USD": 0.138,
        "USD_to_CNY": 7.25
    },
    // 融資通用配置
    finance_terms: {
        "INS01": {
            product_codes: ["C521", "C522", "C523", "C524", "C525"],
            min_finance_amount: 2000000,
            loan_to_value: 0.95,
            base_rate: 0.038,
            processing_fee: 0.01,
            max_loan_term: 30
        },
        "INS02": {
            product_codes: ["T521", "T522", "T523", "T524", "T525"],
            min_finance_amount: 1500000,
            loan_to_value: 0.9,
            base_rate: 0.036,
            processing_fee: 0.008,
            max_loan_term: 25
        }
    },
    // 全量產品數據
    products: [
        {
            id: "P001",
            name: "中國人壽海外 豐盛人生",
            company: "INS01",
            type: "分紅壽險",
            tags: ["高保證回報", "長期持有", "融資適用", "美元計價"],
            currency: "USD",
            premium_term: 5,
            total_premium: 100000,
            guaranteed_return: 0.042,
            non_guaranteed_return: 0.035,
            irr: 0.039,
            break_year: 12,
            influencer_point: "業界最高保證回報率，融資槓桿收益天花板",
            scene_desc: "適合高淨值客戶長期資產配置，搭配廣發銀行融資可放大IRR至6%+",
            risk_level: "低",
            liquidity: "中",
            features: ["保證金額終身鎖定", "分紅率長期穩定", "高靈活融資選項"],
            finance_support: true,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P002",
            name: "中國人壽海外 豐盛人生（升級版）",
            company: "INS01",
            type: "分紅壽險",
            tags: ["靈活繳費", "高流動性", "融資適用", "美元計價"],
            currency: "USD",
            premium_term: 3,
            total_premium: 100000,
            guaranteed_return: 0.038,
            non_guaranteed_return: 0.032,
            irr: 0.035,
            break_year: 10,
            influencer_point: "3年短繳，回本速度業界領先",
            scene_desc: "適合短期資金規劃，3年繳費期滿即可申請融資",
            risk_level: "低",
            liquidity: "高",
            features: ["短繳費期", "快速回本", "靈活贖回"],
            finance_support: true,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P003",
            name: "中國人壽海外 萬用壽險",
            company: "INS01",
            type: "萬用壽險",
            tags: ["高靈活性", "可調整保障", "融資適用", "美元計價"],
            currency: "USD",
            premium_term: "靈活",
            total_premium: 100000,
            guaranteed_return: 0.032,
            non_guaranteed_return: 0.04,
            irr: 0.036,
            break_year: 8,
            influencer_point: "靈活繳費+靈活贖回，現金流管理神器",
            scene_desc: "適合需要靈活調整資金的客戶，可隨時追加或提取資金",
            risk_level: "中低",
            liquidity: "極高",
            features: ["靈活繳費", "靈活提取", "可調整保障額度"],
            finance_support: true,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P004",
            name: "中國人壽海外 終身壽險",
            company: "INS01",
            type: "終身壽險",
            tags: ["高保障", "保本", "低風險", "美元計價"],
            currency: "USD",
            premium_term: 10,
            total_premium: 100000,
            guaranteed_return: 0.035,
            non_guaranteed_return: 0.028,
            irr: 0.032,
            break_year: 15,
            influencer_point: "保本型終身保障，零風險底層資產配置",
            scene_desc: "適合追求絕對保本、長期保障的保守型客戶",
            risk_level: "極低",
            liquidity: "低",
            features: ["100%保本", "終身保障", "固定收益"],
            finance_support: false,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P005",
            name: "中國人壽海外 年金計劃",
            company: "INS01",
            type: "年金險",
            tags: ["固定領取", "退休規劃", "保本", "美元計價"],
            currency: "USD",
            premium_term: 5,
            total_premium: 100000,
            guaranteed_return: 0.037,
            non_guaranteed_return: 0.03,
            irr: 0.034,
            break_year: 11,
            influencer_point: "固定年金領取，退休現金流規劃首選",
            scene_desc: "適合退休規劃，保證終身領取，無需擔心市場波動",
            risk_level: "低",
            liquidity: "中",
            features: ["保證終身領取", "保本", "固定現金流"],
            finance_support: false,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P006",
            name: "中國太平洋人壽 鑫享未來",
            company: "INS02",
            type: "分紅壽險",
            tags: ["高保證回報", "長期持有", "融資適用", "港幣計價"],
            currency: "HKD",
            premium_term: 5,
            total_premium: 100000,
            guaranteed_return: 0.04,
            non_guaranteed_return: 0.033,
            irr: 0.037,
            break_year: 13,
            influencer_point: "港幣計價最高保證回報，本土客戶首選",
            scene_desc: "適合港幣資產配置，搭配廣發銀行港幣融資，放大收益",
            risk_level: "低",
            liquidity: "中",
            features: ["港幣計價", "高保證回報", "穩定分紅"],
            finance_support: true,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P007",
            name: "中國太平洋人壽 鑫享未來（短繳版）",
            company: "INS02",
            type: "分紅壽險",
            tags: ["靈活繳費", "高流動性", "融資適用", "港幣計價"],
            currency: "HKD",
            premium_term: 3,
            total_premium: 100000,
            guaranteed_return: 0.036,
            non_guaranteed_return: 0.03,
            irr: 0.033,
            break_year: 11,
            influencer_point: "3年短繳，港幣產品回本速度領先",
            scene_desc: "適合短期港幣資金規劃，繳費期滿即可申請融資",
            risk_level: "低",
            liquidity: "高",
            features: ["短繳費期", "快速回本", "港幣計價"],
            finance_support: true,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P008",
            name: "中國太平洋人壽 萬用壽險",
            company: "INS02",
            type: "萬用壽險",
            tags: ["高靈活性", "可調整保障", "融資適用", "港幣計價"],
            currency: "HKD",
            premium_term: "靈活",
            total_premium: 100000,
            guaranteed_return: 0.03,
            non_guaranteed_return: 0.038,
            irr: 0.034,
            break_year: 9,
            influencer_point: "靈活繳費+浮動收益，港幣現金流管理神器",
            scene_desc: "適合港幣資金靈活配置，可隨時追加或提取資金",
            risk_level: "中低",
            liquidity: "極高",
            features: ["靈活繳費", "靈活提取", "港幣計價"],
            finance_support: true,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P009",
            name: "中國太平洋人壽 終身壽險",
            company: "INS02",
            type: "終身壽險",
            tags: ["高保障", "保本", "低風險", "港幣計價"],
            currency: "HKD",
            premium_term: 10,
            total_premium: 100000,
            guaranteed_return: 0.034,
            non_guaranteed_return: 0.026,
            irr: 0.031,
            break_year: 16,
            influencer_point: "港幣保本型終身保障，零風險底層資產",
            scene_desc: "適合港幣保本配置，追求絕對安全的保守型客戶",
            risk_level: "極低",
            liquidity: "低",
            features: ["100%保本", "終身保障", "港幣計價"],
            finance_support: false,
            doc_url: "#",
            plan_url: "#"
        },
        {
            id: "P010",
            name: "中國太平洋人壽 年金計劃",
            company: "INS02",
            type: "年金險",
            tags: ["固定領取", "退休規劃", "保本", "港幣計價"],
            currency: "HKD",
            premium_term: 5,
            total_premium: 100000,
            guaranteed_return: 0.036,
            non_guaranteed_return: 0.028,
            irr: 0.033,
            break_year: 12,
            influencer_point: "港幣固定年金，退休規劃首選",
            scene_desc: "適合港幣退休規劃，保證終身領取，穩定現金流",
            risk_level: "低",
            liquidity: "中",
            features: ["保證終身領取", "保本", "港幣計價"],
            finance_support: false,
            doc_url: "#",
            plan_url: "#"
        }
    ],
    // 投資工具對比數據
    investment_tools: [
        {
            name: "銀行定期存款",
            return_rate: 0.025,
            risk_level: "極低",
            liquidity: "中",
            lock_period: "12個月"
        },
        {
            name: "香港政府債券",
            return_rate: 0.032,
            risk_level: "極低",
            liquidity: "高",
            lock_period: "無"
        },
        {
            name: "藍籌股票",
            return_rate: 0.05,
            risk_level: "中",
            liquidity: "極高",
            lock_period: "無"
        },
        {
            name: "房地產投資",
            return_rate: 0.045,
            risk_level: "中",
            liquidity: "低",
            lock_period: "數年"
        },
        {
            name: "保險分紅計劃",
            return_rate: 0.038,
            risk_level: "低",
            liquidity: "中",
            lock_period: "5-10年"
        }
    ]
};
